### ISSUE TITLE
thread '<main>' panicked at 'arithmetic operation overflowed'

### ISSUE THREAD

**Issue by SimonPersson** [PistonDevelopers/image#325]
When I try to load a JPEG file I get the following error:
```
thread '<main>' panicked at 'arithmetic operation overflowed', ./src/jpeg/entropy.rs:147
```
This seems to happen with any JPEG. The issue exists in the `opening.rs` example.

**Comment by TyOverby** [comment]
Are you using the most recent version of the `image` crate?  This should have been fixed a few days ago.

**Comment by SimonPersson** [comment]
Yes, at least as far as I can tell. This happens after I clone the repo, build it and build the `opening.rs` example.

**Comment by zsiciarz** [comment]
Happens for me as well, same error on several JPEGs. [Here](https://travis-ci.org/zsiciarz/24daysofrust/builds/53649955)'s an example build that failed at runtime. (2 days ago, but after the supposed fix)

**Comment by TyOverby** [comment]
Could you provide a backtrace to help diagnose the error?

**Comment by nwin** [comment]
I don’t think we fixed all overflows.

**Comment by zsiciarz** [comment]
Here's a traceback, built with `rustc 1.0.0-nightly (cfea8ec41 2015-03-10) (built 2015-03-11)` and `cargo 0.0.1-pre-nightly (66849de 2015-03-10) (built 2015-03-10)`. The git checkout by cargo is at commit 92a5cec81b08bfd4e829bf0e2873575934d2ee3a.

    ± % RUST_BACKTRACE=1 cargo run --bin=day12                                                                                                      !10040
        Running `target/debug/day12`
    24 days of Rust - image (day 12)
    thread '<main>' panicked at 'arithmetic operation overflowed', /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/jpeg/entropy.rs:147
    stack backtrace:
    1:     0x7f1060269142 - sys::backtrace::write::haa06f2eb4ff4d5e5ADA
    2:     0x7f106026d0b2 - panicking::on_panic::hdcb20beee702c0b03IJ
    3:     0x7f106025ee19 - rt::unwind::begin_unwind_inner::hbe159b4d97e14ee66oJ
    4:     0x7f106025f1c1 - rt::unwind::begin_unwind_fmt::haee4ef7e01d3657fHnJ
    5:     0x7f106026c9d7 - rust_begin_unwind
    6:     0x7f1060298514 - panicking::panic_fmt::h5ce132f2ef412bf4HZs
    7:     0x7f106029843d - panicking::panic::h4135742065e40164TXs
    8:     0x7f106018aa17 - jpeg::entropy::derive_codes_and_sizes::h9fc1744702218dccnhk
                            at /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/jpeg/entropy.rs:147
    9:     0x7f106018d0d6 - jpeg::entropy::derive_tables::h3e1769f62f7e171bulk
                            at /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/jpeg/entropy.rs:173
    10:     0x7f10601eef3a - jpeg::decoder::JPEGDecoder<R>::read_huffman_tables::h4735152126459403654
                            at /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/jpeg/decoder.rs:459
    11:     0x7f10601ed80e - jpeg::decoder::JPEGDecoder<R>::read_metadata::h5388995571800148850
                            at /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/jpeg/decoder.rs:274
    12:     0x7f10601ed2bd - jpeg::decoder::JPEGDecoder<R>.ImageDecoder::colortype::h17242995496453324886
                            at /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/jpeg/decoder.rs:553
    13:     0x7f10601ec278 - dynimage::decoder_to_image::h13845769526475690536
                            at /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/dynimage.rs:423
    14:     0x7f10601c36d2 - dynimage::load::h8503650011569077649
                            at /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/dynimage.rs:559
    15:     0x7f10601c1138 - dynimage::open::h4d9e0b0b0409b7d1fPq
                            at /home/zbyszek/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/dynimage.rs:523
    16:     0x7f10601167a0 - main::haa985ea1b3d1679foaa
                            at src/day12.rs:13
    17:     0x7f10602711f8 - rust_try_inner
    18:     0x7f10602711e5 - rust_try
    19:     0x7f106026e800 - rt::lang_start::h9871739369611a7ejDJ
    20:     0x7f1060117584 - main
    21:     0x7f105fb35ec4 - __libc_start_main
    22:     0x7f10601165c8 - <unknown>
    23:                0x0 - <unknown>
    An unknown error occurred

    To learn more, run the command again with --verbose.

**Comment by SimonPersson** [comment]
This is not solved for me. Here's an image that causes the bug: http://fuskbugg.se/file/deoBTg/P1010529.jpg. Backtrace:
```
~/image $ RUST_BACKTRACE=1 ./opening P1010529.jpg 
thread '<main>' panicked at 'arithmetic operation overflowed', ./src/jpeg/decoder.rs:209
stack backtrace:
   1:     0x7fa9bfefd642 - sys::backtrace::write::haa06f2eb4ff4d5e5ADA
   2:     0x7fa9bff01292 - panicking::on_panic::hdcb20beee702c0b03IJ
   3:     0x7fa9bfef3319 - rt::unwind::begin_unwind_inner::hbe159b4d97e14ee66oJ
   4:     0x7fa9bfef36c1 - rt::unwind::begin_unwind_fmt::h538254dabdf1d6dbHnJ
   5:     0x7fa9bff00bb7 - rust_begin_unwind
   6:     0x7fa9bff2c714 - panicking::panic_fmt::hd9bfa4da86a3b50cHZs
   7:     0x7fa9bff2c63d - panicking::panic::haeeb941f9623f4dfTXs
   8:     0x7fa9bfe9ea4c - jpeg::decoder::JPEGDecoder<R>::decode_mcu::h16681377858681548104
                        at ./src/jpeg/decoder.rs:209
   9:     0x7fa9bfe9df8d - jpeg::decoder::JPEGDecoder<R>::decode_mcu_row::h10512436574909087948
                        at ./src/jpeg/decoder.rs:177
  10:     0x7fa9bfe9da1d - jpeg::decoder::JPEGDecoder<R>.ImageDecoder::read_scanline::h7914295650239136969
                        at ./src/jpeg/decoder.rs:582
  11:     0x7fa9bfe9d3b1 - jpeg::decoder::JPEGDecoder<R>.ImageDecoder::read_image::h3871398705554507924
                        at ./src/jpeg/decoder.rs:606
  12:     0x7fa9bfe94590 - dynimage::decoder_to_image::h7917595641188824261
                        at ./src/dynimage.rs:424
  13:     0x7fa9bfe6b812 - dynimage::load::h8796976204864138992
                        at ./src/dynimage.rs:559
  14:     0x7fa9bfe69278 - dynimage::open::hc6f3ea251803955dmPq
                        at ./src/dynimage.rs:523
  15:     0x7fa9bfdd016f - main::hc384947efbfd4b22iaa
  16:     0x7fa9bff053d8 - rust_try_inner
  17:     0x7fa9bff053c5 - rust_try
  18:     0x7fa9bff029e0 - rt::lang_start::h9871739369611a7ejDJ
  19:     0x7fa9bfdd066e - main
  20:     0x7fa9bf809ad4 - __libc_start_main
  21:     0x7fa9bfdcfee8 - <unknown>
  22:                0x0 - <unknown>
~/image $
```

It seems to be solved for some images though, as nothing worked yesterday and some images have worked today.

**Comment by nwin** [comment]
As a workaround you can just use your program in release mode. This disables the overflow checks.

**Comment by SimonPersson** [comment]
Aha! Thank you, that'll work for now.

**Comment by jarrett** [comment]
Do you anticipate fixing this in the near future? Can I help in some way? While compiling with the `--release` flag is a workaround, it's also a pretty substantial impediment to the programming workflow.

**Comment by nwin** [comment]
This is a annoying bug because it was revealed due to changed overflow semantics in rustc. We anticipate fixing it at some point, we are just missing man power to do that timely. So help is welcome. In principle all shifts and additions have to be replaced by `wrapped_*`. 

I am not sure about the real cause I suppose it is a minor bug in the decoder.

**Comment by jarrett** [comment]
@nwin: I'll be happy to stamp out any overflow panics I can find.

**Comment by nwin** [comment]
closing for now as the known test cases work now after #412 got merged

**Comment by 00shiv** [comment]
I am getting the same panic with 0.3.11. 

thread 'test_cluster_color' panicked at 'arithmetic operation overflowed', /home/shiv/.cargo/registry/src/github.com-0a35038f75765ae4/image-0.3.11/./src/jpeg/entropy.rs:73

Is there a work-around? Thanks. --shiv--

**Comment by SimonPersson** [comment]
@00shiv: Yes, as mentioned earlier, it seems to work if you build in release mode (`cargo build --release`).

**Comment by 00shiv** [comment]
Sorry. I should have added that doing so just moves the error to a slightly later stage.

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("Could not decode symbol.")', ../src/libcore/result.rs:731

**Comment by SimonPersson** [comment]
@00shiv: And you have no unwraps in your own code? Make a backtrace when that error occurs, and you will be more likely to get some help :)

**Comment by 00shiv** [comment]
I do. But I thought it was coming out of the unwrap on the load call. I'll double check. Thanks.
